# Generated by Django 5.2.1 on 2025-05-21 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='prompt_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 15, 39, 47, 946288, tzinfo=datetime.timezone.utc), verbose_name='date_prompted'),
        ),
    ]
