# Generated by Django 5.2.1 on 2025-05-24 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_prompts_prompt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='response',
            field=models.CharField(default='No response', max_length=500),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='prompt_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 10, 8, 14, 618177, tzinfo=datetime.timezone.utc), verbose_name='date_prompted'),
        ),
    ]
